# Generated by Django 4.2.28 on 2026-03-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
