# Generated by Django 4.2.28 on 2026-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(blank=True, default='', max_length=200)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Biography', 'Biography'), ('Dystopian', 'Dystopian'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Technology', 'Technology'), ('Philosophy', 'Philosophy')], max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('cover_image', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
