# Generated by Django 4.2.28 on 2026-03-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
